netfwWCFSoapMVC/MVCClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCClient.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

netfwWCFSoapMVC/MVCClient/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Extensions.Logging;

namespace MVCClient.Controllers
{
    public class PatientController : Controller
    {
        private ILogger _logger = new LoggerFactory().CreateLogger("MVCLocalLogger");

        // GET: Patient
        public ActionResult Index()
        {
            ServiceReference.WcfServiceClient client = new ServiceReference.WcfServiceClient();
            return View(client.GetPatients1());
        }

        public ActionResult Index2()
        {
            ServiceReference.WcfServiceClient client = new ServiceReference.WcfServiceClient();
            return View(client.GetPatients2());
        }

        public ActionResult Index3()
        {
            ServiceReference.WcfServiceClient client = new ServiceReference.WcfServiceClient();
            return View(client.GetPatients3());
        }

        public ActionResult Index4()
        {
            ServiceReference.WcfServiceClient client = new ServiceReference.WcfServiceClient();
            return View(client.GetPatients4());
        }

        public ActionResult Index5()
        {
            ServiceReference.WcfServiceClient client = new ServiceReference.WcfServiceClient();
            var data = client.GetPatients5();
            ViewData["message"] = data;
            return View();
        }
    
        public ActionResult Index6()
        {
            ServiceReference.WcfServiceClient client = new ServiceReference.WcfServiceClient();
            var data = client.GetPatients5();
            ViewData["message"] = data;
            return View();
        }

        public ActionResult Details(int id)
        {
            ServiceReference.WcfServiceClient client = new ServiceReference.WcfServiceClient();
            var allergies = client.GetPatientDetails(id);

            _logger.LogInformation("<mvc client> request details of patient ID {0}", id);

            return View(allergies);
        }

        public ActionResult SendSomethig(int id)
        {
            ServiceReference.WcfServiceClient client = new ServiceReference.WcfServiceClient();
            var whatever = client.SomeSoapData(id);

            return View();
        }

        public ActionResult SendSomethigAgain(int id)
        {
            ServiceReference.WcfServiceClient client = new ServiceReference.WcfServiceClient();
            client.ModifySoapData(id);

            return View();
        }

        public ActionResult OnTextBox()
        {
            ViewData["message"] = "text box has been clicked";
            return View();
        }

        public ActionResult OnTextArea()
        {


            ViewData["message"] = "text area has been clicked";
            return View();
        }
    }
}

netfwWCFSoapMVC/MVCClient/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

netfwWCFSoapMVC/MVCClient/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

netfwWCFSoapMVC/MVCClient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

netfwWCFSoapMVC/MVCClient/Views/Patient/Details.cshtml
@model MVCClient.ServiceReference.Patient

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Allergies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Allergies)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Diagnostics)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diagnostics)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PatientId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

netfwWCFSoapMVC/MVCClient/Views/Patient/Index.cshtml
@model IEnumerable<MVCClient.ServiceReference.Patient>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Allergies)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Diagnostics)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SSID)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Allergies)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diagnostics)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SSID)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.PatientId }) |
                @Html.ActionLink("Details", "Details", new { id = item.PatientId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.PatientId })
            </td>
        </tr>
    }

</table>
<br />
<br />
<br />
<h4>Temporary (WIP)</h4>
<div>
    @Html.Label("this is a label for the text box")
    @Html.TextBox("a text box is here", "abc")
    <input type="button" title="Send" value="Send text BOX input" onclick="location.href='@Url.Action("OnTextBox", "Patient")'" />
</div>
<br />
<div>
    @Html.Label("this is a label for the text box")
    @Html.TextArea("a text area is here")
    <input type="button" title="Send" value="Send text AREA input" onclick="location.href='@Url.Action("OnTextArea", "Patient")'" />
</div>

netfwWCFSoapMVC/MVCClient/Views/Patient/Index2.cshtml
@model IEnumerable<MVCClient.ServiceReference.Patient>

@{
    ViewBag.Title = "Index2";
}

<h2>Index2</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Allergies)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Diagnostics)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SSID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Allergies)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Diagnostics)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SSID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PatientId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PatientId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PatientId })
        </td>
    </tr>
}

</table>

netfwWCFSoapMVC/MVCClient/Views/Patient/Index3.cshtml
@model IEnumerable<MVCClient.ServiceReference.Patient>

@{
    ViewBag.Title = "Index3";
}

<h2>Index3</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Allergies)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Diagnostics)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SSID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Allergies)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Diagnostics)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SSID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PatientId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PatientId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PatientId })
        </td>
    </tr>
}

</table>

netfwWCFSoapMVC/MVCClient/Views/Patient/Index4.cshtml
@model IEnumerable<MVCClient.ServiceReference.Patient>

@{
    ViewBag.Title = "Index4";
}

<h2>Index4</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Allergies)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Diagnostics)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SSID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Allergies)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Diagnostics)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SSID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PatientId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PatientId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PatientId })
        </td>
    </tr>
}

</table>

netfwWCFSoapMVC/MVCClient/Views/Patient/Index5.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index5</title>
</head>
<body>
    <div> 
        @Html.Encode(ViewData["message"])
    </div>
</body>
</html>

netfwWCFSoapMVC/MVCClient/Views/Patient/Index6.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index6</title>
</head>
<body>
    <div>
        @Html.Encode(ViewData["message"])
    </div>
</body>
</html>

netfwWCFSoapMVC/MVCClient/Views/Patient/OnTextBox.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OnTextBox</title>
</head>
<body>
    <div>
        @Html.Encode(ViewData["message"])
    </div>
</body>
</html>

netfwWCFSoapMVC/MVCClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>